FROM node:lts AS builder
WORKDIR /opt/app
COPY package*.json  ./
RUN npm ci --only-production
ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
COPY . .
RUN npm run build

FROM node:lts-alpine AS runner
WORKDIR /opt/app
ARG NODE_ENV
ENV NODE_ENV=$NODE_ENV
ARG PORT
ENV PORT=${PORT}
EXPOSE ${PORT}
COPY --from=builder /opt/app/next.config.js ./
COPY --from=builder /opt/app/public ./public
COPY --from=builder /opt/app/.next ./.next
COPY --from=builder /opt/app/node_modules ./node_modules
CMD ["node_modules/.bin/next", "start"]

