# DEPENDENCY STAGE
FROM node:16.16-slim as builder
WORKDIR /usr/src/app
COPY ./package*.json ./
RUN npm i
COPY ./ ./
RUN npx build-storybook

# STORYBOOK STAGE
FROM httpd:2.4 as storybook
WORKDIR /usr/local/apache2/htdocs/
COPY --from=builder /usr/src/app/storybook-static ./
EXPOSE 80
