FROM node:lts AS dependencies
WORKDIR /opt/app
COPY package*.json  ./
RUN npm ci --only-production

FROM node:lts AS builder
ARG NODE_ENV
ENV NODE_ENV=$NODE_ENV
ARG API_URL
ENV API_URL=$API_URL
WORKDIR /opt/app
COPY . .
COPY --from=dependencies /opt/app/node_modules ./node_modules
RUN npm run build

FROM node:lts-alpine AS runner
WORKDIR /opt/app
ARG NODE_ENV
ENV NODE_ENV=$NODE_ENV
ARG PORT
ENV PORT=${PORT}
EXPOSE ${PORT}
COPY --from=builder /opt/app/next.config.js ./
COPY --from=builder /opt/app/public ./public
COPY --from=builder /opt/app/.next ./.next
COPY --from=builder /opt/app/node_modules ./node_modules
CMD ["node_modules/.bin/next", "start"]

