# DEPENDENCY STAGE
FROM node:slim as dependencies
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm ci

# BUILD STAGE
FROM node:slim as builder
WORKDIR /usr/src/app
COPY --from=dependencies /usr/src/app/node_modules ./node_modules
COPY ./ ./
ARG NODE_ENV
ENV NODE_ENV=$NODE_ENV
ARG API_URL
ENV API_URL=$API_URL
RUN npm run build

# RUN STAGE
FROM node:slim as runner
WORKDIR /usr/src/app
COPY --from=dependencies /usr/src/app/node_modules ./node_modules/
COPY --from=builder /usr/src/app/next.config.js ./
COPY --from=builder /usr/src/app/public ./public
COPY --from=builder /usr/src/app/.next ./.next
COPY --from=builder /usr/src/app/package*.json ./
ARG NODE_ENV
ENV NODE_ENV=$NODE_ENV
ARG API_URL
ENV API_URL=$API_URL
EXPOSE ${PORT}
CMD ["npm", "start"]
