name: CICD - Storybook - GCP
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  deploy-dev:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    environment:
      name: DEV
      url: ${{ steps.deploy.outputs.url }}
    env:
      IMAGE_TAG: us-central1-docker.pkg.dev/me-conta-dev-38ef/me-conta/me-conta-storybook:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - id: 'auth'
        name: Authenticate on GCP
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/615687411435/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider'
          service_account: 'github-actions-service-account@me-conta-dev-38ef.iam.gserviceaccount.com'
      - name: Configure docker client
        run: |-
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
      - name: Build docker image
        run: docker build . -f Dockerfile.storybook -t $IMAGE_TAG
      - name: Push Docker image to registry
        run: docker push $IMAGE_TAG
      - id: deploy
        name: Deploy on Cloud Run
        uses: 'google-github-actions/deploy-cloudrun@v0'
        with:
          region: us-central1
          service: 'me-conta-storybook'
          image: ${{ env.IMAGE_TAG }}